In [ ]:
# standard library imports
import csv
import ast
import datetime as dt
import json
import os
import statistics
import time

# third-party imports
import numpy as np
import pandas as pd
import requests
from collections import Counter 

# customisations - ensure tables show all columns
# pd.set_option("max_columns", 100)

In [ ]:
cd d:\CSC503\project

d:\CSC503\project

In [ ]:
# inspect downloaded steamspy data
df = pd.read_csv('d:/CSC503/project/steam_app_data.csv')
app_list = pd.read_csv('d:/CSC503/project/app_list.csv')

C:\Users\longn\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
app_list.head()

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,852,ValveTestApp852,NaN,NaN,NaN,0,0,0,"0 .. 20,000",0,0,0,0,0.0,0.0,0.0,0
1,1002,Rag Doll Kung Fu,Mark Healey,Mark Healey,NaN,59,25,0,"20,000 .. 50,000",1,0,2,0,99.0,99.0,0.0,0
2,1200,Red Orchestra: Ostfront 41-45,Tripwire Interactive,Tripwire Interactive,NaN,1962,298,0,"500,000 .. 1,000,000",1188,0,342,0,499.0,499.0,0.0,11
3,1300,SiN Episodes: Emergence,Ritual Entertainment,Ritual Entertainment,NaN,788,92,0,"100,000 .. 200,000",65,0,65,0,999.0,999.0,0.0,3
4,1309,SiN Episodes: Emergence,Ritual Entertainment,Ritual Entertainment,NaN,322,45,0,"200,000 .. 500,000",0,0,0,0,999.0,999.0,0.0,0

In [ ]:
df.head()

,type,name,steam_appid,required_age,is_free,controller_support,dlc,detailed_description,about_the_game,short_description,...,categories,genres,screenshots,movies,recommendations,achievements,release_date,support_info,background,content_descriptors
0,NaN,ValveTestApp852,852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,game,Rag Doll Kung Fu,1002,0,False,NaN,NaN,A piece of Steam history - THE FIRST EVER NON ...,A piece of Steam history - THE FIRST EVER NON ...,A piece of Steam history - THE FIRST EVER NON ...,...,"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '23', 'description': 'Indie'}]","[{'id': 0, 'path_thumbnail': 'https://cdn.akam...",NaN,NaN,NaN,"{'coming_soon': False, 'date': '12 Oct, 2005'}","{'url': '', 'email': ''}",https://cdn.akamai.steamstatic.com/steam/apps/...,"{'ids': [], 'notes': None}"
2,game,Red Orchestra: Ostfront 41-45,1200,0,False,NaN,NaN,<h1>D-Day Anniversary 2016 Update for Darkest ...,Fight in the theatre of war that changed the w...,Fight in the theatre of war that changed the w...,...,"[{'id': 1, 'description': 'Multi-player'}, {'i...","[{'id': '1', 'description': 'Action'}]","[{'id': 0, 'path_thumbnail': 'https://cdn.akam...",NaN,{'total': 1278},"{'total': 44, 'highlighted': [{'name': 'Kills ...","{'coming_soon': False, 'date': '14 Mar, 2006'}","{'url': '', 'email': ''}",https://cdn.akamai.steamstatic.com/steam/apps/...,"{'ids': [], 'notes': None}"
3,game,SiN Episodes: Emergence,1300,0,False,NaN,NaN,"You are John Blade, commander of HardCorps, an...","You are John Blade, commander of HardCorps, an...","You are John Blade, commander of HardCorps, an...",...,"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}]","[{'id': 0, 'path_thumbnail': 'https://cdn.akam...",NaN,{'total': 550},NaN,"{'coming_soon': False, 'date': '10 May, 2006'}","{'url': '', 'email': ''}",https://cdn.akamai.steamstatic.com/steam/apps/...,"{'ids': [], 'notes': None}"
4,game,SiN Episodes: Emergence,1300,0,False,NaN,NaN,"You are John Blade, commander of HardCorps, an...","You are John Blade, commander of HardCorps, an...","You are John Blade, commander of HardCorps, an...",...,"[{'id': 2, 'description': 'Single-player'}, {'...","[{'id': '1', 'description': 'Action'}]","[{'id': 0, 'path_thumbnail': 'https://cdn.akam...",NaN,{'total': 550},NaN,"{'coming_soon': False, 'date': '10 May, 2006'}","{'url': '', 'email': ''}",https://cdn.akamai.steamstatic.com/steam/apps/...,"{'ids': [], 'notes': None}"

In [ ]:
merged_inner = pd.merge(left=df, right=app_list, left_on='steam_appid', right_on='appid')

In [ ]:
merged_inner.head()

,type,name_x,steam_appid,required_age,is_free,controller_support,dlc,detailed_description,about_the_game,short_description,...,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
0,NaN,ValveTestApp852,852,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,"0 .. 20,000",0,0,0,0,0.0,0.0,0.0,0
1,game,Rag Doll Kung Fu,1002,0,False,NaN,NaN,A piece of Steam history - THE FIRST EVER NON ...,A piece of Steam history - THE FIRST EVER NON ...,A piece of Steam history - THE FIRST EVER NON ...,...,0,"20,000 .. 50,000",1,0,2,0,99.0,99.0,0.0,0
2,game,Red Orchestra: Ostfront 41-45,1200,0,False,NaN,NaN,<h1>D-Day Anniversary 2016 Update for Darkest ...,Fight in the theatre of war that changed the w...,Fight in the theatre of war that changed the w...,...,0,"500,000 .. 1,000,000",1188,0,342,0,499.0,499.0,0.0,11
3,game,SiN Episodes: Emergence,1300,0,False,NaN,NaN,"You are John Blade, commander of HardCorps, an...","You are John Blade, commander of HardCorps, an...","You are John Blade, commander of HardCorps, an...",...,0,"100,000 .. 200,000",65,0,65,0,999.0,999.0,0.0,3
4,game,SiN Episodes: Emergence,1300,0,False,NaN,NaN,"You are John Blade, commander of HardCorps, an...","You are John Blade, commander of HardCorps, an...","You are John Blade, commander of HardCorps, an...",...,0,"100,000 .. 200,000",65,0,65,0,999.0,999.0,0.0,3

In [ ]:
merged_inner.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 64606 entries, 0 to 64605
Data columns (total 56 columns):
type                       64503 non-null object
name_x                     64599 non-null object
steam_appid                64606 non-null int64
required_age               64503 non-null object
is_free                    64503 non-null object
controller_support         13469 non-null object
dlc                        10258 non-null object
detailed_description       64448 non-null object
about_the_game             64447 non-null object
short_description          64453 non-null object
fullgame                   0 non-null float64
supported_languages        64457 non-null object
header_image               64503 non-null object
website                    34831 non-null object
pc_requirements            64503 non-null object
mac_requirements           64503 non-null object
linux_requirements         64503 non-null object
legal_notice               19637 non-null object
drm_notice                 242 non-null object
ext_user_account_notice    979 non-null object
developers                 64360 non-null object
publishers                 64503 non-null object
demos                      5615 non-null object
price_overview             55176 non-null object
packages                   55775 non-null object
package_groups             64503 non-null object
platforms                  64503 non-null object
metacritic                 3434 non-null object
reviews                    9722 non-null object
categories                 63428 non-null object
genres                     64391 non-null object
screenshots                64409 non-null object
movies                     61841 non-null object
recommendations            13106 non-null object
achievements               35703 non-null object
release_date               64503 non-null object
support_info               64503 non-null object
background                 64416 non-null object
content_descriptors        64503 non-null object
appid                      64606 non-null int64
name_y                     64590 non-null object
developer                  64380 non-null object
publisher                  64462 non-null object
score_rank                 49 non-null float64
positive                   64606 non-null int64
negative                   64606 non-null int64
userscore                  64606 non-null int64
owners                     64606 non-null object
average_forever            64606 non-null int64
average_2weeks             64606 non-null int64
median_forever             64606 non-null int64
median_2weeks              64606 non-null int64
price                      64577 non-null float64
initialprice               64584 non-null float64
discount                   64584 non-null float64
ccu                        64606 non-null int64
dtypes: float64(5), int64(10), object(41)
memory usage: 28.1+ MB

In [ ]:
clean_df = merged_inner[merged_inner.loc[:,"type"].notna()]
drop_columns = ["detailed_description","about_the_game","fullgame"
                ,"website", "background","required_age"
                ,"drm_notice","legal_notice","ext_user_account_notice"
                ,"packages","package_groups","mac_requirements"
                ,"linux_requirements","appid","score_rank","userscore"
                ,"price","initialprice","discount"
                ,"reviews","name_y","positive","negative","support_info"
                ,"dlc","pc_requirements","developer", "publisher"]

clean_df['percent_positive'] = clean_df['positive'].div(clean_df['negative']).replace(np.inf,0).fillna(0)

clean_df = clean_df.drop(columns = drop_columns)

C:\Users\longn\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [ ]:
categorical_change = ["movies","demos","recommendations"]

In [ ]:
def release_date(x):
    now = dt.date.today()
    date = ast.literal_eval(x)['date'][-4:]
    if (now.year - int(date) < 20):
        return 1
    else: 
        return 0

In [ ]:
clean_df.loc[:,"release_date"] = clean_df.loc[:,"release_date"].apply(lambda x: ast.literal_eval(x)['date'])

In [ ]:
clean_df.loc[:,"metacritic"] = clean_df.loc[:,"metacritic"].apply(
    lambda x: None if pd.isnull(x) else ast.literal_eval(x)['score'])

In [ ]:
def categories_function(categories, attr):
    try:
        description = ''
        temp_array = ast.literal_eval(str(categories))
        for object_ar in temp_array:
            description += ", " + object_ar[attr]
        return (description)
    except SyntaxError:
        print("WARNING CATE")
        return str(attr)

In [ ]:
def emptyString(support_info):
    try: 
        car = ast.literal_eval(str(support_info))
        if not car['email'] and not car['url']:
            return 0
        return 1
    except SyntaxError:
        print("WARNING support_info")
        return 1

In [ ]:
def developers_join(developers):
    try: 
        return ', '.join(ast.literal_eval(str(developers)))
    except:
        print("WARNING DEV")
        return str(developers)

In [ ]:
def number_clean(column_to_apply,name):
    try:
        return int(ast.literal_eval(column_to_apply)[name])
    except:
        print("WARNING recommendation or price")
        return 0

In [ ]:
def content_warning_clean(content_descriptors):
    try:
        notes = ast.literal_eval(str(content_descriptors))['notes']
        if not notes:
            return 0
        return 1
    except:
        print("WARNING content_descriptors")
        return 0

In [ ]:
def achivemet_clean(achivemet_clean):
    try:
        total = ast.literal_eval(str(achivemet_clean))['total']
        if not total:
            return 0
        return total
    except:
        print("WARNING achivemet_clean")
        return 0

In [ ]:
def platform(plat):
    temp_str = ''
    new_plat = ast.literal_eval(str(plat))
    wind = new_plat['windows']
    mac = new_plat['mac']
    linux = new_plat['linux']
    if wind == True:
        temp_str += 'windows,'
    if mac == True:
        temp_str += 'mac,'
    if linux == True:
        temp_str += 'linux,'
    return temp_str.rstrip(',')

In [ ]:
clean_df.loc[:,"platforms"] = clean_df.loc[:,"platforms"].apply(
    lambda x: None if pd.isnull(x) else platform(x))

In [ ]:
clean_df.loc[:,"categories"] = clean_df.loc[:,"categories"].apply(
    lambda x: None if pd.isnull(x) else categories_function(x,'description'))

In [ ]:
clean_df.loc[:,"achievements"] = clean_df.loc[:,"achievements"].apply(
    lambda x: 0 if pd.isnull(x) else achivemet_clean(x))

In [ ]:
clean_df.loc[:,"genres"] = clean_df.loc[:,"genres"].apply(
    lambda x: None if pd.isnull(x) else categories_function(x,'description'))

In [ ]:
clean_df.loc[:,"movies"] = clean_df.loc[:,"movies"].apply(lambda x: 0 if pd.isnull(x) else 1)

In [ ]:
clean_df.loc[:,"controller_support"] = clean_df.loc[:,"controller_support"].apply(lambda x: 0 if pd.isnull(x) else 1)

In [ ]:
clean_df.loc[:,"developers"] = clean_df.loc[:,"developers"].apply(lambda x: None if pd.isnull(x) else developers_join(x))
# Some Error with double qoutes so i leave it for now

In [ ]:
clean_df.loc[:,"publishers"] = clean_df.loc[:,"publishers"].apply(lambda x: None if pd.isnull(x) else developers_join(x))

In [ ]:
clean_df.loc[:,"demos"] = clean_df.loc[:,"demos"].apply(lambda x: 0 if pd.isnull(x) else 1)

In [ ]:
clean_df.loc[:,"recommendations"] = clean_df.loc[:,"recommendations"].apply(
    lambda x: 0 if pd.isnull(x) else number_clean(x,"total"))

In [ ]:
clean_df.loc[:,"price_overview"] = clean_df.loc[:,"price_overview"].apply(
    lambda x: 0 if pd.isnull(x) else number_clean(x,"initial"))

In [ ]:
clean_df.loc[:,"content_descriptors"] = clean_df.loc[:,"content_descriptors"].apply(
    lambda x: 0 if pd.isnull(x) else content_warning_clean(x))

In [ ]:
clean_df.loc[:,"is_free"] = clean_df.loc[:,"is_free"].apply(
    lambda x: 1 if x == True else 0)

In [ ]:
clean_df.columns

Index(['type', 'name_x', 'steam_appid', 'is_free', 'controller_support',
       'short_description', 'supported_languages', 'header_image',
       'developers', 'publishers', 'demos', 'price_overview', 'platforms',
       'metacritic', 'categories', 'genres', 'screenshots', 'movies',
       'recommendations', 'achievements', 'release_date',
       'content_descriptors', 'owners', 'average_forever', 'average_2weeks',
       'median_forever', 'median_2weeks', 'ccu', 'percent_positive'],
      dtype='object')

# Steam App Data

'type','name','steam_appid','is_free','controller_support',"short_description", 'supported_languages' (change to cate - English), header_image (convulution),'developers', 'publishers', 'demos', 'price_overview' (only initial) , 'platforms' (change to cate), 'metacritic', 'categories' (top 3),'genres' (top 3), 'movies', 'screenshots', 'recommendations', 'achievements','release_date' (10 years ago vs now),'content_descriptors' (yes or no)

# App List
positive / negative --> percent
appid
name
dev/publisher
owners
both average_ columns
both median_columns 
ccu

In [ ]:
clean_df['supported_languages'] = clean_df['supported_languages'].apply(lambda x: str(x).replace('<strong>*</strong>',""))
clean_df['supported_languages'] = clean_df['supported_languages'].apply(lambda x: str(x).replace('<br>'," "))
clean_df['supported_languages'] = clean_df['supported_languages'].apply(lambda x: str(x).replace('languages with full audio support'," "))
# clean_df['supported_languages'].str.get_dummies(sep=', ')
# clean_df['supported_languages']

In [ ]:
result_df = pd.concat([clean_df, clean_df['platforms'].str.get_dummies(sep=',')], axis = 1).drop('platforms', 1)

In [ ]:
result_df.rename({'name_x': 'name'}, axis=1, inplace=True)

In [ ]:
result_df.head()

,type,name,steam_appid,is_free,controller_support,short_description,supported_languages,header_image,developers,publishers,...,owners,average_forever,average_2weeks,median_forever,median_2weeks,ccu,percent_positive,linux,mac,windows
1,game,Rag Doll Kung Fu,1002,0,0,A piece of Steam history - THE FIRST EVER NON ...,English,https://cdn.akamai.steamstatic.com/steam/apps/...,Mark Healey,Mark Healey,...,"20,000 .. 50,000",1,0,2,0,0,2.360000,0,0,1
2,game,Red Orchestra: Ostfront 41-45,1200,0,0,Fight in the theatre of war that changed the w...,"English, French, Russian",https://cdn.akamai.steamstatic.com/steam/apps/...,Tripwire Interactive,Tripwire Interactive,...,"500,000 .. 1,000,000",1188,0,342,0,11,6.583893,1,1,1
3,game,SiN Episodes: Emergence,1300,0,0,"You are John Blade, commander of HardCorps, an...","English, Russian, French",https://cdn.akamai.steamstatic.com/steam/apps/...,Ritual Entertainment,Ritual Entertainment,...,"100,000 .. 200,000",65,0,65,0,3,8.565217,0,0,1
4,game,SiN Episodes: Emergence,1300,0,0,"You are John Blade, commander of HardCorps, an...","English, Russian, French",https://cdn.akamai.steamstatic.com/steam/apps/...,Ritual Entertainment,Ritual Entertainment,...,"100,000 .. 200,000",65,0,65,0,3,8.565217,0,0,1
5,game,SiN: Gold,1313,0,0,SiN: Gold has returned! Free update for origin...,"English, French",https://cdn.akamai.steamstatic.com/steam/apps/...,"Ritual Entertainment, Nightdive Studios",Nightdive Studios,...,"0 .. 20,000",10,0,11,0,2,6.075000,0,0,1

In [ ]:
def bagFunction(column_name):
    bag_of_words = []
    for row in result_df[column_name].values:
        if (row != None):
            temp = row.strip().split(", ")
            bag_of_words = bag_of_words + temp
#         bag_of_words = list(filter(None, bag_of_words))
    return bag_of_words

In [ ]:
# lang = bagFunction('supported_languages')
bag_of_languages = Counter(bagFunction('supported_languages')).most_common(3)

In [ ]:
# result_df['supported_languages'].head()
# result_df['supported_languages'].values.flatten()
german = bag_of_languages[1][0]
french = bag_of_languages[2][0]
english = bag_of_languages[0][0]
column_english = result_df['supported_languages'].apply(lambda x: 1 if english in x else 0)
column_english.name  = 'English'
column_german = result_df['supported_languages'].apply(lambda x: 1 if german in x else 0)
column_french = result_df['supported_languages'].apply(lambda x: 1 if french in x else 0)
column_german.name  = 'German'
column_french.name  = 'French'

In [ ]:
result_df = pd.concat([result_df,column_french,column_english,column_german],axis=1, join='inner')
result_df = result_df.drop(columns = ["supported_languages"])
result_df.head()

,type,name,steam_appid,is_free,controller_support,short_description,header_image,developers,publishers,demos,...,median_forever,median_2weeks,ccu,percent_positive,linux,mac,windows,French,English,German
1,game,Rag Doll Kung Fu,1002,0,0,A piece of Steam history - THE FIRST EVER NON ...,https://cdn.akamai.steamstatic.com/steam/apps/...,Mark Healey,Mark Healey,1,...,2,0,0,2.360000,0,0,1,0,1,0
2,game,Red Orchestra: Ostfront 41-45,1200,0,0,Fight in the theatre of war that changed the w...,https://cdn.akamai.steamstatic.com/steam/apps/...,Tripwire Interactive,Tripwire Interactive,0,...,342,0,11,6.583893,1,1,1,1,1,0
3,game,SiN Episodes: Emergence,1300,0,0,"You are John Blade, commander of HardCorps, an...",https://cdn.akamai.steamstatic.com/steam/apps/...,Ritual Entertainment,Ritual Entertainment,0,...,65,0,3,8.565217,0,0,1,1,1,0
4,game,SiN Episodes: Emergence,1300,0,0,"You are John Blade, commander of HardCorps, an...",https://cdn.akamai.steamstatic.com/steam/apps/...,Ritual Entertainment,Ritual Entertainment,0,...,65,0,3,8.565217,0,0,1,1,1,0
5,game,SiN: Gold,1313,0,0,SiN: Gold has returned! Free update for origin...,https://cdn.akamai.steamstatic.com/steam/apps/...,"Ritual Entertainment, Nightdive Studios",Nightdive Studios,0,...,11,0,2,6.075000,0,0,1,1,1,0
6,game,Darwinia,1500,0,1,Combining fast-paced action with strategic bat...,https://cdn.akamai.steamstatic.com/steam/apps/...,Introversion Software,Introversion Software,0,...,10,0,8,3.705000,1,1,1,1,1,1
7,game,Uplink,1510,0,0,You play an Uplink Agent who makes a living by...,https://cdn.akamai.steamstatic.com/steam/apps/...,Introversion Software,Introversion Software,0,...,49,0,5,10.598930,1,1,1,0,1,0
8,game,DEFCON,1520,0,0,"Inspired by the 1983 cult classic film, Wargam...",https://cdn.akamai.steamstatic.com/steam/apps/...,Introversion Software,Introversion Software,1,...,42,0,28,6.614072,1,1,1,1,1,1
9,game,Multiwinia,1530,0,0,&quot;Long ago a computer scientist called Dr ...,https://cdn.akamai.steamstatic.com/steam/apps/...,Introversion Software,Introversion Software,1,...,179,0,3,4.541667,0,1,1,1,1,1
10,game,Dangerous Waters,1600,0,0,S.C.S. - Dangerous Waters allows you total con...,https://cdn.akamai.steamstatic.com/steam/apps/...,Sonalysts,Strategy First,0,...,143,0,3,3.302632,0,0,1,0,1,0
11,game,Space Empires IV Deluxe,1610,0,0,The award-winning Space Empires IV Deluxe is t...,https://cdn.akamai.steamstatic.com/steam/apps/...,Malfador Machinations,Strategy First,0,...,169,0,16,5.342857,0,0,1,0,1,0
12,game,Disciples II: Rise of the Elves,1630,0,0,The award-winning series Disciples introduced ...,https://cdn.akamai.steamstatic.com/steam/apps/...,Strategy First,Strategy First,0,...,15,0,40,6.141892,0,0,1,0,1,0
13,game,Disciples II: Gallean's Return,1640,0,0,Disciples II: Gallean's Return is a compilatio...,https://cdn.akamai.steamstatic.com/steam/apps/...,Strategy First,Strategy First,0,...,699,0,54,4.467890,0,0,1,0,1,0
14,game,Iron Warriors: T - 72 Tank Command,1670,0,0,The most devastating mechanized armor to ever ...,https://cdn.akamai.steamstatic.com/steam/apps/...,Strategy First,Strategy First,0,...,4,0,0,1.669903,0,0,1,0,1,0
15,game,Space Empires V,1690,0,0,Space Empires V is the latest edition in the S...,https://cdn.akamai.steamstatic.com/steam/apps/...,Malfador Machinations,Strategy First,0,...,1122,0,8,2.415254,0,0,1,0,1,0
16,game,Arx Fatalis,1700,0,0,This critically acclaimed first-person RPG fro...,https://cdn.akamai.steamstatic.com/steam/apps/...,Arkane Studios,Arkane Studios,1,...,40,0,27,6.783251,0,0,1,1,1,1
17,game,Earth 2160,1900,0,0,"After the destruction of the EARTH in 2150, th...",https://cdn.akamai.steamstatic.com/steam/apps/...,Reality Pump Studios,"Topware Interactive, ACE",0,...,423,0,11,2.363388,1,1,1,1,1,1
18,game,Quake III Arena,2200,0,0,The greatest warriors of all time and space ha...,https://cdn.akamai.steamstatic.com/steam/apps/...,id Software,id Software,0,...,286,0,25,21.439394,0,0,1,0,1,0
19,game,Quake 4,2210,0,0,"As part of the elite Rhino Squad, you must spe...",https://cdn.akamai.steamstatic.com/steam/apps/...,"RavenSoft, id Software",Bethesda Softworks,0,...,71,0,16,7.071429,0,0,1,0,1,0
20,game,Wolfenstein 3D,2270,0,0,World War II rages. The Nazis are planning to ...,https://cdn.akamai.steamstatic.com/steam/apps/...,id Software,Bethesda Softworks,0,...,20,0,13,15.331551,0,0,1,0,1,0
21,game,Final DOOM,2290,0,0,"Two New, 32-Level DOOM II Episodes. Evilution:...",https://cdn.akamai.steamstatic.com/steam/apps/...,id Software,id Software,0,...,3,0,5,5.897727,0,0,1,0,1,0
22,game,DOOM II,2300,0,1,"Hell has invaded Earth, and to save it, you mu...",https://cdn.akamai.steamstatic.com/steam/apps/...,id Software,id Software,0,...,13,9,87,18.600000,0,0,1,1,1,1
23,game,Quake II,2320,0,0,"Mankind is at war with the Strogg, a hostile a...",https://cdn.akamai.steamstatic.com/steam/apps/...,id Software,id Software,0,...,59,1,28,10.347403,0,0,1,0,1,0
24,game,Quake II Mission Pack: The Reckoning,2330,0,0,You are part of an elite commando force that m...,https://cdn.akamai.steamstatic.com/steam/apps/...,Xatrix Entertainment,id Software,0,...,1,0,0,4.363636,0,0,1,0,1,0
25,game,Quake II Mission Pack: Ground Zero,2340,0,0,"Take out the Big Gun sounded simple enough, ex...",https://cdn.akamai.steamstatic.com/steam/apps/...,Rogue Entertainment,id Software,0,...,1,0,0,1.458824,0,0,1,0,1,0
26,game,Hexen: Beyond Heretic,2360,0,0,While the Sidhe elf Corvus battled the evil fo...,https://cdn.akamai.steamstatic.com/steam/apps/...,Raven Software,id Software,0,...,38,1,3,8.066667,0,0,1,0,1,0
27,game,Hexen: Deathkings of the Dark Citadel,2370,0,0,Hexen: Deathkings of the Dark Citadel is a dar...,https://cdn.akamai.steamstatic.com/steam/apps/...,Raven Software,id Software,0,...,19,0,1,3.424242,0,0,1,0,1,0
28,game,Heretic: Shadow of the Serpent Riders,2390,0,0,In a realm corrupted by the evil magic of thre...,https://cdn.akamai.steamstatic.com/steam/apps/...,Raven Software,id Software,0,...,7,0,8,15.764706,0,0,1,0,1,0
29,game,The Ship: Single Player,2420,0,0,The Ship is a murder mystery alternative to tr...,https://cdn.akamai.steamstatic.com/steam/apps/...,Outerlight Ltd.,Blazing Griffin Ltd.,0,...,61,0,2,2.390977,0,0,1,1,1,1
30,game,Bloody Good Time,2450,0,0,"Congratulations, you’ve just been cast in your...",https://cdn.akamai.steamstatic.com/steam/apps/...,Outerlight Ltd.,Ubisoft,0,...,129,0,1,3.443439,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64576,game,骸心 Mainbody,2189420,0,0,A puzzle-based horror game where the player ta...,https://cdn.akamai.steamstatic.com/steam/apps/...,水硅钒钙,冷笑黑妖,0,...,0,0,0,0.000000,0,0,1,0,0,0
64577,game,Mission: Aliens,2189750,0,0,"Sergeant, last night we received a signal that...",https://cdn.akamai.steamstatic.com/steam/apps/...,STuNT,STuNT,0,...,0,0,0,0.000000,0,0,1,0,1,0
64578,game,Blocks Tracks Trains,2190250,0,0,A relaxing sandbox train set diorama. Build yo...,https://cdn.akamai.steamstatic.com/steam/apps/...,splenbit,splenbit,0,...,0,0,1,0.000000,1,0,1,0,1,0
64579,game,VR Painting: Time,2190500,0,0,This is a Virtual Reality painting experience....,https://cdn.akamai.steamstatic.com/steam/apps/...,Joshua N Stanton,Joshua N Stanton,0,...,0,0,0,0.000000,0,0,1,0,1,0
64580,game,WEAPONEER,2190880,0,0,A Ball... A Sword &amp; A Dream.,https://cdn.akamai.steamstatic.com/steam/apps/...,PLUG_WORLD,"VoxPop Games, Inc.",0,...,0,0,0,0.000000,0,0,1,0,1,0
64581,game,WORDKOUR,2190950,0,0,WORDKOUR - Are You a Parkour Enthusiast Who al...,https://cdn.akamai.steamstatic.com/steam/apps/...,Archor Wright,Archor Games,0,...,0,0,0,1.000000,0,0,1,0,1,0
64582,game,Little Devil,2191180,0,0,Little Devil is a survival horror game for up ...,https://cdn.akamai.steamstatic.com/steam/apps/...,QUIKGAMES,QUIKGAMES,0,...,0,0,2,1.000000,0,0,1,0,1,0
64583,game,Little Devil,2191180,0,0,Little Devil is a survival horror game for up ...,https://cdn.akamai.steamstatic.com/steam/apps/...,QUIKGAMES,QUIKGAMES,0,...,0,0,2,1.000000,0,0,1,0,1,0
64584,game,Little Devil,2191180,0,0,Little Devil is a survival horror game for up ...,https://cdn.akamai.steamstatic.com/steam/apps/...,QUIKGAMES,QUIKGAMES,0,...,0,0,2,1.000000,0,0,1,0,1,0
64585,game,Little Devil,2191180,0,0,Little Devil is a survival horror game for up ...,https://cdn.akamai.steamstatic.com/steam/apps/...,QUIKGAMES,QUIKGAMES,0,...,0,0,2,1.000000,0,0,1,0,1,0
64586,game,The Exorcist's Story,2191460,0,0,"You are in the role of a young priest Antonio,...",https://cdn.akamai.steamstatic.com/steam/apps/...,Seaborgium Entertainment,Seaborgium Entertainment,0,...,0,0,0,0.000000,0,0,1,0,1,0
64587,game,IronKnight,2191530,0,0,The sky roared and the flames of the city cont...,https://cdn.akamai.steamstatic.com/steam/apps/...,AHui.Game,AHui.Game,0,...,0,0,0,0.000000,0,0,1,1,1,1
64588,game,PESTICIDE,2191920,0,1,PESTICIDE is a raw reflex action FPS that puts...,https://cdn.akamai.steamstatic.com/steam/apps/...,Nuclear Dog team,Nuclear Dog team,0,...,0,0,1,0.000000,0,0,1,0,1,0
64589,game,The Iron Union,2192640,0,1,"Greetings tank commander,and welcome to the《Th...",https://cdn.akamai.steamstatic.com/steam/apps/...,Horn of the sea,Horn of the sea,0,...,0,0,1,0.000000,1,0,1,0,1,0
64590,game,The Iron Union,2192640,0,1,"Greetings tank commander,and welcome to the《Th...",https://cdn.akamai.steamstatic.com/steam/apps/...,Horn of the sea,Horn of the sea,0,...,0,0,1,0.000000,1,0,1,0,1,0
64591,game,The Iron Union,2192640,0,1,"Greetings tank commander,and welcome to the《Th...",https://cdn.akamai.steamstatic.com/steam/apps/...,Horn of the sea,Horn of the sea,0,...,0,0,1,0.000000,1,0,1,0,1,0
64592,game,The Iron Union,2192640,0,1,"Greetings tank commander,and welcome to the《Th...",https://cdn.akamai.steamstatic.com/steam/apps/...,Horn of the sea,Horn of the sea,0,...,0,0,1,0.000000,1,0,1,0,1,0
64593,game,Super Clown 3: Revenge,2192650,0,0,Sorcerer and his army has captured Stars who k...,https://cdn.akamai.steamstatic.com/steam/apps/...,"Tero Lunkka, Valkeala Software",Tero Lunkka,0,...,0,0,1,4.333333,0,0,1,0,1,0
64594,game,Funplace: After Hours,2193170,0,0,"In this point and click horror game, you will ...",https://cdn.akamai.steamstatic.com/steam/apps/...,MMM Games,MMM Games,0,...,0,0,0,0.000000,0,0,1,0,1,0
64595,game,Cocktail Rush,2193580,0,0,Cocktail Rush is a match 3 game with visual no...,https://cdn.akamai.steamstatic.com/steam/apps/...,Crooked Road,Piece Of Voxel,0,...,0,0,0,9.000000,0,0,1,0,1,0
64596,game,SPEEDRUNNER,2193690,0,0,"The title says it all, SPEEDRUNNER. Run, fast,...",https://cdn.akamai.steamstatic.com/steam/apps/...,Speed Development,Speed Development,0,...,0,0,0,0.000000,0,0,1,0,1,0
64597,game,Monster Hunters: Frost Giant,2193990,0,0,Follow the exciting adventures of this monster...,https://cdn.akamai.steamstatic.com/steam/apps/...,Lamonade Games,Lamonade Games,0,...,0,0,1,0.000000,0,0,1,0,1,0
64598,game,Idle Hamburgers Save the World,2194410,0,0,Your goal is just to keep producing hamburgers...,https://cdn.akamai.steamstatic.com/steam/apps/...,okyakusama,okyakusama,0,...,0,0,3,3.000000,0,0,1,1,1,1
64599,game,Find The Key,2195200,0,0,A strange game with skeletons and giant aliens.,https://cdn.akamai.steamstatic.com/steam/apps/...,eddysss games,eddysss games,0,...,0,0,0,0.000000,0,0,1,1,1,1
64600,game,Find The Key,2195200,0,0,A strange game with skeletons and giant aliens.,https://cdn.akamai.steamstatic.com/steam/apps/...,eddysss games,eddysss games,0,...,0,0,0,0.000000,0,0,1,1,1,1
64601,game,Find The Key,2195200,0,0,A strange game with skeletons and giant aliens.,https://cdn.akamai.steamstatic.com/steam/apps/...,eddysss games,eddysss games,0,...,0,0,0,0.000000,0,0,1,1,1,1
64602,game,Find The Key,2195200,0,0,A strange game with skeletons and giant aliens.,https://cdn.akamai.steamstatic.com/steam/apps/...,eddysss games,eddysss games,0,...,0,0,0,0.000000,0,0,1,1,1,1
64603,game,Barren Depths,2196100,0,0,Escape a confusing cave system without being e...,https://cdn.akamai.steamstatic.com/steam/apps/...,Kyle Obranovic,Kyle Obranovic,0,...,0,0,0,0.000000,0,0,1,0,1,0
64604,game,Mining Copper,2197500,0,0,Collect copper ore and pass through various sm...,https://cdn.akamai.steamstatic.com/steam/apps/...,Fire,Fire,0,...,0,0,6,1.000000,0,0,1,0,1,0
64605,game,Cursor Engine,2201210,0,0,Tired of the traditional boring cursor? Use Cu...,https://cdn.akamai.steamstatic.com/steam/apps/...,RainySoft,RainySoft,0,...,0,0,6,0.000000,0,0,1,0,1,0

In [ ]:
genres_test = bagFunction('genres')
# bag_of_genres = Counter(bagFunction('genres')).most_common(3)

In [ ]:
genres_te = list(filter(None, genres_test))
bag_of_genres = Counter(genres_te).most_common(3)
bag_of_genres

[('Indie', 46334), ('Action', 27268), ('Casual', 25850)]

In [ ]:
Action = bag_of_genres[1][0]
Casual = bag_of_genres[2][0]
Indie = bag_of_genres[0][0]
column_indie = result_df['genres'].apply(lambda x: 0 if x is None else (1 if Indie in x else 0) )
column_indie.name  = 'Indie'
column_Casual = result_df['genres'].apply(lambda x: 0 if x is None else (1 if Casual in x else 0))
column_Action = result_df['genres'].apply(lambda x: 0 if x is None else (1 if Indie in x else 0))
column_Casual.name  = 'Casual'
column_Action.name  = 'Action'

In [ ]:
keep_df = result_df

In [ ]:
result_df = pd.concat([result_df,column_indie,column_Casual,column_Action],axis=1, join='inner')
result_df = result_df.drop(columns = ["genres"])
result_df.head()

,type,name,steam_appid,is_free,controller_support,short_description,header_image,developers,publishers,demos,...,percent_positive,linux,mac,windows,French,English,German,Indie,Casual,Action
1,game,Rag Doll Kung Fu,1002,0,0,A piece of Steam history - THE FIRST EVER NON ...,https://cdn.akamai.steamstatic.com/steam/apps/...,Mark Healey,Mark Healey,1,...,2.360000,0,0,1,0,1,0,1,0,1
2,game,Red Orchestra: Ostfront 41-45,1200,0,0,Fight in the theatre of war that changed the w...,https://cdn.akamai.steamstatic.com/steam/apps/...,Tripwire Interactive,Tripwire Interactive,0,...,6.583893,1,1,1,1,1,0,0,0,0
3,game,SiN Episodes: Emergence,1300,0,0,"You are John Blade, commander of HardCorps, an...",https://cdn.akamai.steamstatic.com/steam/apps/...,Ritual Entertainment,Ritual Entertainment,0,...,8.565217,0,0,1,1,1,0,0,0,0
4,game,SiN Episodes: Emergence,1300,0,0,"You are John Blade, commander of HardCorps, an...",https://cdn.akamai.steamstatic.com/steam/apps/...,Ritual Entertainment,Ritual Entertainment,0,...,8.565217,0,0,1,1,1,0,0,0,0
5,game,SiN: Gold,1313,0,0,SiN: Gold has returned! Free update for origin...,https://cdn.akamai.steamstatic.com/steam/apps/...,"Ritual Entertainment, Nightdive Studios",Nightdive Studios,0,...,6.075000,0,0,1,1,1,0,0,0,0

In [ ]:
def checkRel(x):
    try:
        if (int(x[-4:])<2010):
            return 1
        else:
            return 0
    except ValueError:
        return 0

In [ ]:
result_df.loc[:,"release_date"] = keep_df.loc[:,"release_date"].apply(lambda x: 1 if checkRel(x) == 1 else 0)

In [ ]:
result_df=result_df.rename(columns = {'release_date':'released 10 years ago'})

In [ ]:
cat_test = bagFunction('categories')

In [ ]:
ca_te = list(filter(None, cat_test))
bag_of_cat = Counter(ca_te).most_common(3)
bag_of_cat

[('Single-player', 60404),
 ('Steam Achievements', 31521),
 ('Steam Cloud', 15993)]

In [ ]:
Achievements = bag_of_cat[1][0]
Cloud = bag_of_cat[2][0]
Single = bag_of_cat[0][0]
column_Single = result_df['categories'].apply(lambda x: 0 if x is None else (1 if Single in x else 0) )
column_Single.name  = 'Single'
column_Cloud = result_df['categories'].apply(lambda x: 0 if x is None else (1 if Cloud in x else 0))
column_Achievements = result_df['categories'].apply(lambda x: 0 if x is None else (1 if Achievements in x else 0))
column_Cloud.name  = 'Cloud'
column_Achievements.name  = 'Achievements'

In [ ]:
result_df = pd.concat([result_df,column_Single,column_Cloud,column_Achievements],axis=1, join='inner')
result_df = result_df.drop(columns = ["categories"])
result_df.head()

,type,name,steam_appid,is_free,controller_support,short_description,header_image,developers,publishers,demos,...,windows,French,English,German,Indie,Casual,Action,Single,Cloud,Achievements
1,game,Rag Doll Kung Fu,1002,0,0,A piece of Steam history - THE FIRST EVER NON ...,https://cdn.akamai.steamstatic.com/steam/apps/...,Mark Healey,Mark Healey,1,...,1,0,1,0,1,0,1,1,0,0
2,game,Red Orchestra: Ostfront 41-45,1200,0,0,Fight in the theatre of war that changed the w...,https://cdn.akamai.steamstatic.com/steam/apps/...,Tripwire Interactive,Tripwire Interactive,0,...,1,1,1,0,0,0,0,0,0,1
3,game,SiN Episodes: Emergence,1300,0,0,"You are John Blade, commander of HardCorps, an...",https://cdn.akamai.steamstatic.com/steam/apps/...,Ritual Entertainment,Ritual Entertainment,0,...,1,1,1,0,0,0,0,1,0,0
4,game,SiN Episodes: Emergence,1300,0,0,"You are John Blade, commander of HardCorps, an...",https://cdn.akamai.steamstatic.com/steam/apps/...,Ritual Entertainment,Ritual Entertainment,0,...,1,1,1,0,0,0,0,1,0,0
5,game,SiN: Gold,1313,0,0,SiN: Gold has returned! Free update for origin...,https://cdn.akamai.steamstatic.com/steam/apps/...,"Ritual Entertainment, Nightdive Studios",Nightdive Studios,0,...,1,1,1,0,0,0,0,1,0,0

In [ ]:
result_df.to_csv('out.csv',index=False)